#!/usr/bin/env python3
import json
import urllib.request
import sys
BASE_URL = "https://jisho.org/api/v1/search/words?keyword="

def cobbler(definitions):
    empty_list = []
    for defe in definitions:
        empty_list.append(defe)
    print(', '.join(empty_list)) 

if len(sys.argv) == 1:
    print("Correct usage: jisho word_to_search")
    sys.exit(0)
else:
    resp = urllib.request.Request(BASE_URL+urllib.request.quote(sys.argv[1]))
    data = json.load(urllib.request.urlopen(BASE_URL+urllib.request.quote(sys.argv[1])))

if not data['data']:
    print('Nothing Found')
    sys.exit(0)
for response in data['data']:
    test = response['japanese'][0]
    if 'word' in test:
        print(test['word'] + "[" + test.get('reading',"") + "]")
    else:
        print(test['reading'])
    if (len(response['japanese'])>1):
        print("Other Forms")
        for word in response['japanese'][1:]:
            if 'word' in word:
                print(word['word'] + "[" + word.get('reading',"") + "]")
            else:
                print(word['reading'])
    print("Definitions")
    for idx,meaning in enumerate(response['senses']):
        print(str(idx+1) + ". ")
        cobbler(meaning['english_definitions'])
    print("=" * 80,end='\n')
#pprint(data['data'])
