#!/usr/bin/env python3
import json
import urllib.request
import sys
BASE_URL = "https://jisho.org/api/v1/search/words?keyword="

def exit(whatToPrint):
    print(whatToPrint)
    sys.exit(0)

def cobbler(definitions):
    empty_list = []
    for defe in definitions:
        empty_list.append(defe)
    print(', '.join(empty_list)) 

if len(sys.argv) == 1:
    exit("Correct usage: jisho word_to_search")
else:
    try:
        response = urllib.request.urlopen(BASE_URL+urllib.request.quote(sys.argv[1]))
    except urllib.error.URLError as e:
        exit(str(e.__dict__['reason'])[11:])

data = json.load(response)
if not data['data']:
    exit('Nothing Found')
for response in data['data']:
    test = response['japanese'][0]
    if 'word' in test:
        print(test['word'] + "[" + test.get('reading',"") + "]")
    else:
        print(test['reading'])
    if (len(response['japanese'])>1):
        print("Other Forms")
        for word in response['japanese'][1:]:
            if 'word' in word:
                print(word['word'] + "[" + word.get('reading',"") + "]")
            else:
                print(word['reading'])
    print("Definitions")
    for idx,meaning in enumerate(response['senses']):
        print(str(idx+1) + ". ",end='')
        cobbler(meaning['english_definitions'])
    print("=" * 80,end='\n')