#!/usr/bin/env python
# Checks what games are available on the Overwatch Arcade

import json
import urllib2
from pprint import pprint
URL = "https://overwatcharcade.today/api/today"
hdr = {'User-Agent':'Mozilla/5.0'}
req = urllib2.Request(URL,headers=hdr)
data = json.load(urllib2.urlopen(req))
print "Today's Arcade\n***********************************************\nDaily"
print "Game : " + data["tile_large"]["name"] + "\nPlayers: " + data["tile_large"]["players"]
print "==============================================="
print "Game: "+data["tile_daily"]["name"] + "\nPlayers : " + data["tile_daily"]["players"]
print "***********************************************\n***********************************************\nWeekly"
print "Game : " + data["tile_weekly_1"]["name"] + "\nPlayers: " + data["tile_weekly_1"]["players"]
print "==============================================="
print "Game : " + data["tile_weekly_2"]["name"] + "\nPlayers: " + data["tile_weekly_2"]["players"]
print "***********************************************\n***********************************************\nPermanent"
print "Game: " + data["tile_permanent"]["name"] + "\nPlayers: " + data["tile_permanent"]["players"]
print "***********************************************"
